### PR TITLE
click-odoo-update: add dry-run option to evaluate addons to update before actually updating.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This allows to anticipate better the impact of an update. Let me know if this approach is correct and/or if it needs any change.

Awesome project BTW :)

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
I have just updated this to solve conflicts generate by the last release.

@sbidoul Hopefully can you have a word here? It have been proven very useful for me, but maybe  there are drawbacks I am not foreseeing.

**Comment by LoisRForgeFlow** [comment]
@sbidoul Great, I've attended your comments, `--list-only` makes sense for me, I've applied that.

**Comment by sbidoul** [comment]
LGTM, thanks! Would you mind updating the documentation in the README and adding a file named `68.feature` with a short changelog entry in the [newsfragment](https://github.com/acsone/click-odoo-contrib/tree/master/newsfragments) directory?

**Comment by sbidoul** [comment]
@LoisRForgeFlow also, add yourself to the contributors list.

**Comment by LoisRForgeFlow** [comment]
@sbidoul Done! thanks.

**Comment by LoisRForgeFlow** [comment]
Seems that test are failling, I had problems running them in local, how should I install `tox`, I did `pip install tox`, is that what is expected?

**Comment by sbidoul** [comment]
The test error is fairly obvious in the travis log :) Don't look at the last job with Odoo master though: that one is red and it's normal - something changed in Odoo that we'll need to investigate before v14 is out.

Regarding installing tox, I like using [pipx](https://pypi.org/project/pipx/), but it should not matter much. `pip install --user tox` should work too. What's problem do you have with local tests?

**Comment by LoisRForgeFlow** [comment]
I just wanted to make it work also in local, I had a problem with dependencies.

All green now. Thanks for your help :)

**Pull request merged**
