### PR TITLE
Makepot: Add --modules option

### LINKED ISSUE #92: click-odoo-makepot: Add --modules option
It will be usefull to have --modules option to update only concrete modules pot files

### PR DESCRIPTION
**Pull request by voronind**
Resolves #92

### CODE REVIEW

**Comment by voronind** [comment]
Do I wait for fixing tests?

**Comment by sbidoul** [comment]
Thanks. Please 
- [ ] rebase
- [ ] update README
- [ ] add newsfragment/92.feature

**Comment by voronind** [comment]
> Thanks. Please
> 
> * [ ]  rebase
> * [ ]  update README
> * [ ]  add newsfragment/92.feature

Done

**Comment by sbidoul** [comment]
Looks good, thank you very much!

**Pull request merged**
