### PR TITLE
backupdb: Allows to specify the db schema to backup.

### LINKED ISSUE #37: click-odoo-backupdb: dump does not exlude non public data
https://stackoverflow.com/questions/10169203/postgresql-9-1-pg-restore-error-regarding-plpgsql

debugging output:
```
 /usr/bin/pg_restore --dbname=click-odoo-contrb-testbackupdb --no-owner /tmp/pytest-of-blaggacao/pytest-273/tests_backupdb_folder_restore1/backup/db.dump
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 4684; 0 0 COMMENT EXTENSION plpgsql 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';



WARNING: errors ignored on restore: 1
```

### PR DESCRIPTION
**Pull request by lmignon**
fixes #37

### CODE REVIEW

**Comment by sbidoul** [comment]
@lmignon rebasing should get you a green build (#46). Strangely enough, the backup test error we have seen do not appear anymore?

**Comment by lmignon** [comment]
> @lmignon rebasing should get you a green build (#46). Strangely enough, the backup test error we have seen do not appear anymore?

Rebase done. Indeed, strange. Don't understand why the error has disappeared.

**Comment by sbidoul** [comment]
Putting this in WIP for now since I'm not sure what we are fixing exactly

**Comment by lmignon** [comment]
@sbidoul OK. Indeed, even if I had errors without these changes previously on ma machine, I'm no more have troubles without these.... Maybe a problem into pg_dump.

**Comment by lmignon** [comment]
closing since this bug seems to no more occurs

**Pull request closed without merging**
